// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: daemonServer.proto

#include "daemonServer.pb.h"
#include "daemonServer.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace daemon_server {

static const char* DaemonServer_method_names[] = {
  "/daemon_server.DaemonServer/ClientRegister",
};

std::unique_ptr< DaemonServer::Stub> DaemonServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DaemonServer::Stub> stub(new DaemonServer::Stub(channel));
  return stub;
}

DaemonServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_ClientRegister_(DaemonServer_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DaemonServer::Stub::ClientRegister(::grpc::ClientContext* context, const ::daemon_server::ClientRegisterRequest& request, ::daemon_server::ClientRegisterReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ClientRegister_, context, request, response);
}

void DaemonServer::Stub::experimental_async::ClientRegister(::grpc::ClientContext* context, const ::daemon_server::ClientRegisterRequest* request, ::daemon_server::ClientRegisterReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ClientRegister_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::daemon_server::ClientRegisterReply>* DaemonServer::Stub::AsyncClientRegisterRaw(::grpc::ClientContext* context, const ::daemon_server::ClientRegisterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::daemon_server::ClientRegisterReply>::Create(channel_.get(), cq, rpcmethod_ClientRegister_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::daemon_server::ClientRegisterReply>* DaemonServer::Stub::PrepareAsyncClientRegisterRaw(::grpc::ClientContext* context, const ::daemon_server::ClientRegisterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::daemon_server::ClientRegisterReply>::Create(channel_.get(), cq, rpcmethod_ClientRegister_, context, request, false);
}

DaemonServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DaemonServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DaemonServer::Service, ::daemon_server::ClientRegisterRequest, ::daemon_server::ClientRegisterReply>(
          std::mem_fn(&DaemonServer::Service::ClientRegister), this)));
}

DaemonServer::Service::~Service() {
}

::grpc::Status DaemonServer::Service::ClientRegister(::grpc::ServerContext* context, const ::daemon_server::ClientRegisterRequest* request, ::daemon_server::ClientRegisterReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace daemon_server

